name: Ruby Gem - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3
        bundler-cache: true
    - name: Build and Test
      run: |
        go build -v -buildmode=c-shared -o proxy/planetscale-linux.so
        bundle exec rake test
