name: Ruby Gem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  

jobs:
  build:
    name: Build + Publish
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV   

    - name: Build shared library on OS X
      run: go build -v -buildmode=c-shared -o proxy/psdb-darwin.so

    - name: Build shared library on Linux
      run: docker run -v $(pwd):/psdb-ruby golang sh -c 'cd /psdb-ruby && go build -v -buildmode=c-shared -o proxy/psdb-linux.so'

    - name: Publish to GPR
      run: |
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_BUILD: 1
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
